#!/bin/bash
# ============================================================
# create-issue.sh — GitHub Issue 自動生成
# ============================================================
# Usage: ./create-issue.sh <TITLE> [BODY] [LABEL]
#
# 環境変数:
#   GH_TOKEN or GITHUB_TOKEN — GitHub API トークン
# ============================================================
set -euo pipefail

# --- 引数チェック ---
if [ $# -lt 1 ]; then
    echo "Usage: $0 <TITLE> [BODY] [LABEL]" >&2
    exit 1
fi

TITLE="$1"
BODY="${2:-Auto-generated by ClaudeOS}"
LABEL="${3:-auto-generated}"

# --- 入力バリデーション ---
if [ ${#TITLE} -gt 256 ]; then
    echo "Error: Title too long (max 256 chars)" >&2
    exit 1
fi

if [ ${#BODY} -gt 65536 ]; then
    echo "Error: Body too long (max 65536 chars)" >&2
    exit 1
fi

# --- 重複チェック（同タイトルのopen issueが24時間以内にあればスキップ） ---
EXISTING=$(gh issue list \
    --state open \
    --search "$TITLE" \
    --json number,title,createdAt \
    --limit 5 2>/dev/null | \
    python3 -c "
import json, sys
from datetime import datetime, timezone, timedelta
issues = json.load(sys.stdin)
now = datetime.now(timezone.utc)
for i in issues:
    created = datetime.fromisoformat(i['createdAt'].replace('Z', '+00:00'))
    if i['title'] == '''$TITLE''' and (now - created) < timedelta(hours=24):
        print(i['number'])
        break
" 2>/dev/null || echo "")

if [ -n "$EXISTING" ]; then
    echo "Skipped: Similar issue #$EXISTING already exists (within 24h)"
    exit 0
fi

# --- Issue 作成 ---
ISSUE_URL=$(gh issue create \
    --title "$TITLE" \
    --body "$BODY" \
    --label "$LABEL" 2>&1)

echo "Created: $ISSUE_URL"
