#!/bin/bash
# ============================================================
# create-pr.sh — GitHub PR 自動生成（WorkTree連動）
# ============================================================
# Usage: ./create-pr.sh [BASE_BRANCH]
#
# 現在のブランチから BASE_BRANCH (default: main) への PR を作成
#
# 環境変数:
#   GH_TOKEN or GITHUB_TOKEN — GitHub API トークン
# ============================================================
set -euo pipefail

BASE="${1:-main}"
BRANCH=$(git branch --show-current)

# --- バリデーション ---
if [ "$BRANCH" = "$BASE" ]; then
    echo "Error: Cannot create PR from $BASE to $BASE" >&2
    exit 1
fi

if [ -z "$BRANCH" ]; then
    echo "Error: Not on any branch (detached HEAD?)" >&2
    exit 1
fi

# --- 未コミット変更チェック ---
if ! git diff --quiet 2>/dev/null; then
    echo "Warning: Uncommitted changes detected" >&2
fi

# --- リモートに push ---
echo "Pushing $BRANCH to origin..."
git push -u origin "$BRANCH" 2>&1 || {
    echo "Error: Push failed" >&2
    exit 1
}

# --- 既存PR チェック ---
EXISTING_PR=$(gh pr list --head "$BRANCH" --base "$BASE" --json number -q '.[0].number' 2>/dev/null || echo "")
if [ -n "$EXISTING_PR" ]; then
    echo "PR already exists: #$EXISTING_PR"
    echo "https://github.com/$(gh repo view --json nameWithOwner -q '.nameWithOwner')/pull/$EXISTING_PR"
    exit 0
fi

# --- コミットログから PR 説明生成 ---
COMMITS=$(git log "$BASE".."$BRANCH" --oneline 2>/dev/null || echo "- Initial commit")
COMMIT_COUNT=$(echo "$COMMITS" | wc -l)

# --- PR 作成 ---
PR_URL=$(gh pr create \
    --title "Auto PR: $BRANCH" \
    --body "$(cat <<EOF
## Summary
Auto-generated by ClaudeOS ($COMMIT_COUNT commits)

## Changes
$COMMITS

## Test
- Local tests: pending CI verification

## CI
- Pending

---
🤖 Generated with ClaudeOS Pipeline
EOF
)" \
    --base "$BASE" \
    --head "$BRANCH" 2>&1)

echo "Created: $PR_URL"
