#!/bin/bash
# detect-ip.sh - 実行環境のIPアドレスを自動検出して .env.runtime に書き出す
# Systemd ExecStartPre / 手動起動どちらからも利用可能
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
RUNTIME_ENV="${PROJECT_ROOT}/.env.runtime"

# ─────────────────────────────────────────
# IPアドレス自動検出
# 優先順: デフォルトルートのNIC → 最初の非loopbackアドレス → 127.0.0.1
# ─────────────────────────────────────────
detect_primary_ip() {
    local ip=""

    # 方法1: デフォルトルートが使用するNICのIPを取得
    if command -v ip >/dev/null 2>&1; then
        local iface
        iface=$(ip route show default 2>/dev/null | awk '/default via/ {print $5}' | head -1)
        if [[ -n "${iface}" ]]; then
            ip=$(ip -4 addr show "${iface}" 2>/dev/null | awk '/inet / {print $2}' | cut -d'/' -f1 | head -1)
        fi
    fi

    # 方法2: 外部疎通確認 (UDP trick - パケット送信なし)
    if [[ -z "${ip}" ]]; then
        ip=$(python3 -c "
import socket
try:
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(('8.8.8.8', 80))
    print(s.getsockname()[0])
    s.close()
except Exception:
    print('')
" 2>/dev/null || echo "")
    fi

    # 方法3: 最初の非loopbackアドレス
    if [[ -z "${ip}" ]] && command -v hostname >/dev/null 2>&1; then
        ip=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "")
    fi

    # フォールバック
    if [[ -z "${ip}" ]]; then
        ip="127.0.0.1"
    fi

    echo "${ip}"
}

PRIMARY_IP=$(detect_primary_ip)

# ─────────────────────────────────────────
# 環境変数読み込み（既存 .env を参照）
# ─────────────────────────────────────────
DEV_PORT="${DEV_PORT:-5012}"
DEV_HTTPS_PORT="${DEV_HTTPS_PORT:-5443}"
PROD_PORT="${PROD_PORT:-8000}"
PROD_HTTPS_PORT="${PROD_HTTPS_PORT:-8443}"

if [[ -f "${PROJECT_ROOT}/.env" ]]; then
    # .env から不足変数を補完（セキュリティ上 eval は使わず grep で取得）
    _val=$(grep "^DEV_PORT=" "${PROJECT_ROOT}/.env" 2>/dev/null | cut -d'=' -f2 || echo "")
    [[ -n "${_val}" ]] && DEV_PORT="${_val}"
    _val=$(grep "^DEV_HTTPS_PORT=" "${PROJECT_ROOT}/.env" 2>/dev/null | cut -d'=' -f2 || echo "")
    [[ -n "${_val}" ]] && DEV_HTTPS_PORT="${_val}"
    _val=$(grep "^PROD_PORT=" "${PROJECT_ROOT}/.env" 2>/dev/null | cut -d'=' -f2 || echo "")
    [[ -n "${_val}" ]] && PROD_PORT="${_val}"
    _val=$(grep "^PROD_HTTPS_PORT=" "${PROJECT_ROOT}/.env" 2>/dev/null | cut -d'=' -f2 || echo "")
    [[ -n "${_val}" ]] && PROD_HTTPS_PORT="${_val}"
fi

# ─────────────────────────────────────────
# .env.runtime に書き出し
# ─────────────────────────────────────────
cat > "${RUNTIME_ENV}" << EOF
# Auto-generated by detect-ip.sh at $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# DO NOT EDIT - regenerated on every start

DETECTED_IP=${PRIMARY_IP}

# Development
DEV_IP=0.0.0.0
DEV_BIND_HOST=${PRIMARY_IP}
DEV_PORT=${DEV_PORT}
DEV_HTTPS_PORT=${DEV_HTTPS_PORT}
DEV_BASE_URL=http://${PRIMARY_IP}:${DEV_PORT}
DEV_HTTPS_BASE_URL=https://${PRIMARY_IP}:${DEV_HTTPS_PORT}
DEV_API_BASE_URL=http://${PRIMARY_IP}:${DEV_PORT}/api

# Production
PROD_IP=0.0.0.0
PROD_BIND_HOST=${PRIMARY_IP}
PROD_PORT=${PROD_PORT}
PROD_HTTPS_PORT=${PROD_HTTPS_PORT}
PROD_BASE_URL=http://${PRIMARY_IP}:${PROD_PORT}
PROD_HTTPS_BASE_URL=https://${PRIMARY_IP}:${PROD_HTTPS_PORT}
PROD_API_BASE_URL=https://${PRIMARY_IP}:${PROD_HTTPS_PORT}/api
EOF

chmod 600 "${RUNTIME_ENV}"

echo "✅ IP検出完了: ${PRIMARY_IP}"
echo "   開発URL:   http://${PRIMARY_IP}:${DEV_PORT}  /  https://${PRIMARY_IP}:${DEV_HTTPS_PORT}"
echo "   本番URL:   http://${PRIMARY_IP}:${PROD_PORT}  /  https://${PRIMARY_IP}:${PROD_HTTPS_PORT}"
echo "   設定保存: ${RUNTIME_ENV}"
